spring:
  datasource:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://localhost:3306/vsc_portal?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
      username: root
      password: root
#      password: 1Qaz.2WSx


mybatis-plus:
  mapper-locations: classpath:mappers/**/*Mapper.xml

