#spring:
#  mail:
#    host: smtp.163.com
#    port: 465
#    username: mrh100353@163.com
#    # 使用 jasypt 加密密码，使用com.xkcoding.email.PasswordTest.testGeneratePassword 生成加密密码，替换 ENC(加密密码)
#    password: WAVUPMPBMIVUIHXV
#    protocol: smtp
#    test-connection: true
#    default-encoding: UTF-8
#    properties:
#      mail.smtp.auth: true
#      mail.smtp.starttls.enable: true
#      mail.smtp.starttls.required: true
#      mail.smtp.ssl.enable: true
#      mail.display.sendmail: spring-boot-demo
## 为 jasypt 配置解密秘钥
#jasypt:
#  encryptor:
#    password: mrh100353

spring:
  datasource:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://localhost:3306/vsc_portal?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
      username: root
      password: root
#      password: 1Qaz.2WSx


mybatis-plus:
  mapper-locations: classpath:mappers/**/*Mapper.xml

